New Features: Sprint 13
Siustoster/java-shareit pull request #1
Opened 2024-04-27 15:55 UTC by Siustoster

Items controllers
User controllers

2024-04-28 12:31 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
CONFLICT

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
private financial

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@AllArgsConstructor
RequiredArgsConstructor

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") int userId, @RequestBody @Valid ItemDto item) {
"X-Sharer-User-Id" -- это давайте в константу вынесем

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@AllArgsConstructor
RequiredArgsConstructor

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private Item mapDtoToItem(ItemDto item, int itemId, int ownerId) {
этот и 2 метода давайте вынесем в какой-нибудь mapper класс

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> itemsFounded = itemStorage.getAllUserItems(userId);
```
return itemStorage.getAllUserItems(userId).stream()
        .map(item -> mapItemtoDto(item))
        .collect(Collector.toList());
```

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> itemsFounded = itemStorage.searchItem(text);
смотрите коммент выше

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public ItemDto getItemById(int userId, int itemId) {
getItemByIdAndUserId(int id, int userId)

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private Item getItem(int id) {
почему не паблик?

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +        List<Item> itemsFounded = new ArrayList<>();
давайте через stream api

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +        List<Item> itemsFounded = new ArrayList<>();
тоже через stream api

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +@AllArgsConstructor
RequiredArgsConstructor

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@AllArgsConstructor
RequiredArgsConstructor

2024-04-28 12:31 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserStorageInMemory.java
> +
лишний отступ

2024-04-28 16:26 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
Не понял на счёт financial

2024-04-30 09:27 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Тогда не проходим проверку теста постман 
![image](https://github.com/Siustoster/java-shareit/assets/144737921/935021c6-68fa-4046-aa55-9bdd11fdd00a)
 
он требует, что бы при ошибке с апдейтом вещи был код 404 или 403

2024-04-30 09:38 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
Исправлено

2024-04-30 09:38 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +@AllArgsConstructor
Исправлено

2024-04-30 09:38 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") int userId, @RequestBody @Valid ItemDto item) {
Исправлено

2024-04-30 09:38 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@AllArgsConstructor
Исправлено

2024-04-30 09:41 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/user/UserStorageInMemory.java
> +
Исправлено

2024-04-30 09:42 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@AllArgsConstructor
Исправлено

2024-04-30 09:43 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +@AllArgsConstructor
Исправлено

2024-04-30 09:43 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +        List<Item> itemsFounded = new ArrayList<>();
Исправлено

2024-04-30 09:44 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +        List<Item> itemsFounded = new ArrayList<>();
Исправлено

2024-04-30 09:52 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public ItemDto getItemById(int userId, int itemId) {
Исправлено

2024-04-30 09:59 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private Item mapDtoToItem(ItemDto item, int itemId, int ownerId) {
Исправлено

2024-04-30 10:47 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> itemsFounded = itemStorage.getAllUserItems(userId);
Исправлено

2024-04-30 10:47 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> itemsFounded = itemStorage.searchItem(text);
Исправлено

2024-04-30 11:33 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
только перед мержем поправьте комменты

2024-04-30 11:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
убрать

2024-04-30 11:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private ItemService itemService;
private final

2024-04-30 11:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +@Service
лучше @Component, под @Service подразумевается бизнес логика

2024-04-30 11:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public Item mapDtoToItem(ItemDto item, int itemId, int ownerId) {
также можно методы сделать статиком методы

2024-06-03 19:03 UTC, merged