Sprint 15 first iteration
Siustoster/java-shareit pull request #3
Opened 2024-06-20 20:00 UTC by Siustoster

2024-06-27 13:49 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил пару комментов

2024-06-27 13:49 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>                                    @RequestParam(defaultValue = "false") String approved) {
можно сразу Boolean передать

2024-06-27 13:49 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getRequestId() != null && itemDto.getRequestId() > 0)
а если itemDto.getRequestId()  или меньше или равно 0??

2024-06-27 13:49 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size < 1)
давайте эту проверку уберем в какой-нибудь utility класс и будем применять для всех контроллеров

2024-06-27 16:03 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>                                    @RequestParam(defaultValue = "false") String approved) {
Исправлено

2024-06-27 16:03 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getRequestId() != null && itemDto.getRequestId() > 0)
Исправлено

2024-06-27 16:03 UTC, Siustoster commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0 || size < 1)
Исправлено

2024-06-28 08:23 UTC, ErkinKasymaliev approved these changes
привет, коммент поправьте и можете мержить

2024-06-28 08:23 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/ShareitUtility.java
> +public class ShareitUtility {
лучше PageableUtility

2024-07-04 19:15 UTC, merged